#!/usr/bin/bash

printf "Enter Url:(www.example.com)"
read url



echo "==============================      ==================================="
echo "============================== DirB ==================================="
echo "==============================      ==================================="
dirb(){
	
	dirb http://$url -r -z 1000
}


echo "============================ Nikto ================================"

nikto(){


	echo "show cookies and response 200 ..."
	nikto -host $url -Display 23V # Show cookies and response 200
	echo "Show SQL injection"
	nikto -host $url -Tuning 9 # SQL injection Test 
	echo "show intersting File and misconfigurations and information Disclosure and Injection(XSS/Script/HTML)"
	nikto -host $url -Tuning 1234


}


nmap(){
	echo "Start Scan Server ports ..."
	ip=`nslookup realsepta.ir | grep Address | tail -1 | awk '{print $2}'`
	nmap -Pn $ip

}

loadbalancer(){
	echo "Try to Detect LoadBalancer in Server"
	lbd www.realsepta.ir
}

webapp_firrewall(){
	echo "Try to find WAF in Server ..."
	wafw00f www.realsepta.ir
}








